In [1]:
import dhlab as dh
import pandas as pd
import gensim
import pyLDAvis
from pprint import pprint
import pyLDAvis.gensim_models as genvis

In [2]:
# sprit urn URN:NBN:no-nb_digibok_2020090207537

In [3]:
bok = dh.Corpus(doctype="digibok", limit=1, title="Norgeshistorie")

In [4]:
bok

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,100360073,URN:NBN:no-nb_digibok_2017121908100,HB : en destillert norgeshistorie,"Eggen , Torgrim / Bertelsen , Jon / Høynes , Rudi",oai:nb.bibsys.no:991509499794702202,d72246db1c54eea8e279b5ae20052cb0,,,20150101,2015,Cappelen Damm,mul / nob / nno,Alkohol / Brennevin / Tradisjoner,394.13 / 364.133209481,,Faglitteratur,digibok,nb,20060101

In [5]:
urn = bok.frame.urn.tolist()[0]
urn

'URN:NBN:no-nb_digibok_2017121908100'

In [6]:
# Chunks 
res = dh.Chunks(chunks=1000, urn=urn)

In [7]:
len(res.chunks)

90

In [8]:
def chunks_to_corpus(chunks_list):
    res = []
    for x in chunks_list:
        inner_res = ""
        for y in x:
            inner_res += (y + " ") * x[y]
            
        res.append(inner_res)
    return res

In [9]:
texts = chunks_to_corpus(res.chunks)

In [10]:
df = pd.DataFrame(res.chunks).transpose().fillna(0)

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,...,80,81,82,83,84,85,86,87,88,89
(,3.0,4.0,2.0,0.0,10.0,4.0,4.0,14.0,5.0,1.0,...,4.0,5.0,2.0,2.0,5.0,6.0,11.0,3.0,4.0,4.0
),3.0,4.0,2.0,0.0,10.0,4.0,4.0,14.0,5.0,1.0,...,4.0,5.0,2.0,2.0,5.0,6.0,12.0,3.0,4.0,5.0
",",47.0,36.0,38.0,55.0,41.0,35.0,42.0,42.0,37.0,47.0,...,40.0,45.0,43.0,49.0,38.0,48.0,40.0,36.0,42.0,49.0
-,4.0,7.0,4.0,2.0,7.0,4.0,2.0,2.0,2.0,3.0,...,1.0,9.0,4.0,5.0,7.0,7.0,1.0,12.0,8.0,3.0
.,43.0,44.0,57.0,59.0,39.0,66.0,56.0,49.0,48.0,54.0,...,54.0,43.0,56.0,53.0,46.0,45.0,44.0,51.0,57.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
vinkel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
whiskydestilleri,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
whiskymerker,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
ølbryggerutstyr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
øya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [12]:
# Import top 50000 tokens from NB collection
tot = dh.totals(50000)

In [13]:
# Divide corpus freq count by tot
res = df.sum(axis=1) /  tot.freq

In [14]:
# Get top 1000 more frequent tokens
target_tokens = res.sort_values(ascending=False).iloc[:1000].dropna().index

In [15]:
df.loc[target_tokens]

,0,1,2,3,4,5,6,7,8,9,...,80,81,82,83,84,85,86,87,88,89
sprit,0.0,0.0,1.0,1.0,2.0,0.0,0.0,5.0,1.0,0.0,...,1.0,0.0,6.0,2.0,0.0,1.0,1.0,0.0,2.0,4.0
Gryllefjord,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
gjær,1.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
brennevinet,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
satsen,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
kull,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
kjøkkensjef,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Prytz,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
simpelthen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TV-serien,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
outer_lst = []

for col in df.loc[target_tokens].columns:
    inner_str = ""
    for i, x in df.loc[target_tokens][col].items():
        if x > 0:
            inner_str += (i + " ") * int(x)
        
    outer_lst.append(inner_str)

In [17]:
len(outer_lst)

90

In [18]:
data = [x.split() for x in outer_lst]

In [19]:
id2word = gensim.corpora.Dictionary(data)

In [20]:
corpus = [id2word.doc2bow(chunk) for chunk in data]

In [21]:
lda_model = gensim.models.LdaMulticore(
    corpus = corpus,
    id2word = id2word,
    num_topics = 10
)

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

/home/tita/.local/share/uv/python/cpython-3.13.3-linux-x86_64-gnu/lib/python3.13/multiprocessing/popen_fork.py:67: DeprecationWarning: This process (pid=8612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()

In [22]:
pprint(lda_model.print_topics())

[(0,
  '0.023*"alkohol" + 0.018*"brennevin" + 0.017*"liter" + 0.016*"va" + '
  '0.014*"drikke" + 0.010*"sprit" + 0.009*"satsen" + 0.009*"kaller" + '
  '0.008*"dram" + 0.008*"drikker"'),
 (1,
  '0.027*"brennevin" + 0.013*"konjakk" + 0.012*"sprit" + 0.011*"gjær" + '
  '0.010*"sukker" + 0.010*"alkohol" + 0.009*"brus" + 0.009*"drikke" + '
  '0.009*"liter" + 0.009*"Hallstein"'),
 (2,
  '0.019*"alla" + 0.018*"moder" + 0.014*"dår" + 0.014*"my" + 0.013*"alkohol" + '
  '0.010*"behover" + 0.009*"came" + 0.007*"223" + 0.006*"Hætta" + '
  '0.006*"NTNU"'),
 (3,
  '0.031*"sprit" + 0.021*"brennevin" + 0.021*"alkohol" + 0.014*"Aarrestad" + '
  '0.012*"sats" + 0.012*"176" + 0.011*"øl" + 0.010*"HB" + 0.010*"vin" + '
  '0.009*"pleide"'),
 (4,
  '0.028*"Melhus" + 0.026*"liter" + 0.025*"sprit" + 0.022*"va" + 0.017*"bygda" '
  '+ 0.014*"brennevin" + 0.013*"drikke" + 0.012*"HB" + 0.012*"bryllup" + '
  '0.011*"sats"'),
 (5,
  '0.031*"sprit" + 0.019*"alkohol" + 0.018*"va" + 0.015*"brennevin" + '
  '0.012*"kaffe" + 0.009*"produktet" + 0.009*"flaske" + 0.009*"sats" + '
  '0.009*"drikke" + 0.009*"vin"'),
 (6,
  '0.037*"sprit" + 0.021*"brennevin" + 0.015*"Gryllefjord" + 0.013*"cl" + '
  '0.011*"sukker" + 0.011*"flasker" + 0.010*"Brita" + 0.009*"Johnson" + '
  '0.009*"HB" + 0.009*"apparat"'),
 (7,
  '0.032*"brennevin" + 0.024*"sprit" + 0.023*"kaffe" + 0.020*"sukker" + '
  '0.018*"liter" + 0.017*"alkohol" + 0.015*"drikker" + 0.011*"Tim" + '
  '0.011*"Gryllefjord" + 0.009*"HB"'),
 (8,
  '0.034*"alkohol" + 0.014*"176" + 0.014*"sukker" + 0.013*"bygda" + '
  '0.013*"brennevin" + 0.011*"fins" + 0.011*"671" + 0.011*"sprit" + '
  '0.011*"sats" + 0.010*"apparatet"'),
 (9,
  '0.031*"liter" + 0.024*"sprit" + 0.021*"sukker" + 0.021*"brennevin" + '
  '0.013*"va" + 0.011*"Bernt" + 0.010*"Popcorn" + 0.010*"alkohol" + '
  '0.010*"itj" + 0.010*"sats"')]

In [23]:
prep = genvis.prepare(lda_model, corpus, id2word)

In [24]:
# Save to html
# pyLDAvis.save_html(prep, "result.html")

In [25]:
pyLDAvis.enable_notebook()

In [26]:
pyLDAvis.display(prep)